// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Payloads.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Telemetries : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Telemetries\",\"namespace\":\"Payloads.Avro\",\"fields\":[{\"nam" +
				"e\":\"temperature\",\"type\":\"double\"},{\"name\":\"WorkingSet\",\"type\":\"double\"}]}");
		private double _temperature;
		private double _WorkingSet;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Telemetries._SCHEMA;
			}
		}
		public double temperature
		{
			get
			{
				return this._temperature;
			}
			set
			{
				this._temperature = value;
			}
		}
		public double WorkingSet
		{
			get
			{
				return this._WorkingSet;
			}
			set
			{
				this._WorkingSet = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.temperature;
			case 1: return this.WorkingSet;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.temperature = (System.Double)fieldValue; break;
			case 1: this.WorkingSet = (System.Double)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
